# -*- coding: utf-8 -*-
"""FINAL_MODEL_JENNIFER_FYP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HCCt6sO5XLZ5ieYDwbxj4pPWSb0sBEx

# EEG-Based ASD Classification — GWO + XGBoost (Subject-Level)
"""

# ================================================================
# CELL 1 — Imports
# ================================================================

import random, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

from sklearn.model_selection import StratifiedKFold, cross_val_score, learning_curve, train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler
from sklearn.impute import KNNImputer
from sklearn.metrics import (
    accuracy_score, f1_score, roc_auc_score,
    classification_report, confusion_matrix, roc_curve,
    precision_recall_fscore_support, matthews_corrcoef, cohen_kappa_score
)
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import VarianceThreshold
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

import xgboost as xgb
from imblearn.over_sampling import SMOTE
import shap

SEED = 42
random.seed(SEED); np.random.seed(SEED)

# ================================================================
# CELL 2 — Load Data
# ================================================================

CSV_PATH     = '/content/features_sheffield_v3 - features_sheffield_v3.csv.csv'
SUBJECT_COL  = 'Subject'
LABEL_COL    = 'Label'

df_raw = pd.read_csv(CSV_PATH)
subjects = df_raw[SUBJECT_COL].tolist()
print(f'Loaded: {df_raw.shape[0]} rows × {df_raw.shape[1]} columns')

print('\nSample subject names:', df_raw[SUBJECT_COL].head(4).tolist())

df_raw.head(3)

# ================================================================
# CELL 3 — Preprocessing & Train/Test Split
# ================================================================

df = df_raw.drop(columns=[SUBJECT_COL]).copy()

le = LabelEncoder()
df[LABEL_COL] = le.fit_transform(df[LABEL_COL])
print(f'Classes: {le.classes_} → {list(range(len(le.classes_)))}')

X_raw = df.drop(columns=[LABEL_COL]).apply(pd.to_numeric, errors='coerce')
y     = df[LABEL_COL].values.astype(int)

# Variance filter
vt        = VarianceThreshold(threshold=1e-8)
X_vt      = vt.fit_transform(X_raw)
kept_cols = X_raw.columns[vt.get_support()]
X_df      = pd.DataFrame(X_vt, columns=kept_cols)
print(f'Features after variance filter: {X_df.shape[1]} / {X_raw.shape[1]}')


USE_SMOTE    = False

X_full        = X_df.values
feature_names = list(X_df.columns)
n_samples, n_features = X_full.shape
n_classes     = len(le.classes_)
print(f'\nFinal: {n_samples} subjects × {n_features} features | {n_classes} classes')

# Train/Test Split (20% held-out test set)
n = len(y)
train_indices, test_indices = train_test_split(
    range(n), test_size=0.2, stratify=y, random_state=SEED
)
X_train_full = X_full[train_indices]
X_test = X_full[test_indices]
y_train_full = y[train_indices]
y_test = y[test_indices]
print(f'\n--- Train/Test Split ---')
print(f'Train: {X_train_full.shape[0]} subjects | Test: {X_test.shape[0]} subjects')
test_subjects = [subjects[i] for i in test_indices]
print("Test subjects:", test_subjects)

# ================================================================
# CELL 4 — Exploratory Data Analysis (Train Set Only)
# ================================================================
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

ax = axes[0]
train_counts = [Counter(y_train_full)[k] for k in sorted(Counter(y_train_full))]
ax.bar(le.classes_, train_counts, color=['steelblue', 'tomato'])
ax.set_title('Subject-Level Class Distribution (Train Set)')
ax.set_ylabel('Subjects')
for i, v in enumerate(train_counts):
    ax.text(i, v + 0.1, str(v), ha='center', fontweight='bold')

ax = axes[1]
ax.hist((X_raw.isna().mean() * 100).values, bins=20, color='slategray', edgecolor='white')
ax.set_title('NaN % per Feature'); ax.set_xlabel('% NaN'); ax.set_ylabel('Features')

ax = axes[2]
ax.hist(np.nanmax(X_train_full, axis=0) - np.nanmin(X_train_full, axis=0), bins=30,
        color='mediumseagreen', edgecolor='white')
ax.set_title('Feature Value Ranges (Train)'); ax.set_xlabel('Max - Min'); ax.set_ylabel('Count')

plt.tight_layout()
plt.savefig('eda_overview.png', bbox_inches='tight')
plt.show()

top_idx = np.argsort(np.var(X_train_full, axis=0))[-20:]
top_df  = pd.DataFrame(X_train_full[:, top_idx], columns=[feature_names[i] for i in top_idx])
top_df['Label'] = y_train_full
plt.figure(figsize=(14, 10))
corr = top_df.corr()
sns.heatmap(corr, mask=np.triu(np.ones_like(corr, dtype=bool)),
            cmap='coolwarm', center=0, annot=False, linewidths=0.3)
plt.title('Correlation Matrix (Top 20 Features by Variance, Train Set)')
plt.tight_layout()
plt.savefig('correlation_heatmap.png', bbox_inches='tight')
plt.show()

# ================================================================
# CELL 5 — GWO Feature Selection (Training Set Only)
# ================================================================

GWO_FS_WOLVES = 30
GWO_FS_ITER   = 80
GWO_FS_ALPHA  = 0.9
GWO_FS_CV     = 5
GWO_FS_THRESH = 0.5

def _make_eval_model():
  return xgb.XGBClassifier(
      n_estimators=100, max_depth=3, learning_rate=0.1,
      subsample=0.8, colsample_bytree=0.8, min_child_weight=3,
      eval_metric='logloss', random_state=SEED, tree_method='hist'
      )

def fitness_fs(mask, X, y):
  sel = np.where(mask > GWO_FS_THRESH)[0]
  if len(sel) == 0: return 1.0
  pipe = Pipeline([('sc', RobustScaler()), ('clf', _make_eval_model())])
  cv   = StratifiedKFold(n_splits=GWO_FS_CV, shuffle=True, random_state=SEED)
  acc  = cross_val_score(pipe, X[:, sel], y, cv=cv, scoring='accuracy', n_jobs=-1).mean()
  return (1 - GWO_FS_ALPHA) * (len(sel)/X.shape[1]) + GWO_FS_ALPHA * (1 - acc)

def gwo_feature_selection(X, y, n_wolves=GWO_FS_WOLVES, max_iter=GWO_FS_ITER):
  n_feat = X.shape[1]
  wolves = np.random.rand(n_wolves, n_feat)  # Initialize positions randomly [0,1]
  apos, ascore = np.zeros(n_feat), float('inf')  # Best wolf (α)
  bpos, bscore = np.zeros(n_feat), float('inf')  # 2nd best wolf (β)
  dpos, dscore = np.zeros(n_feat), float('inf')  # 3rd best wolf (δ)
  history = []

  for t in range(max_iter):
    for i in range(n_wolves):
      s = fitness_fs(wolves[i], X, y)
      # Update three best wolves
      if s < ascore:
        dscore, dpos = bscore, bpos.copy()
        bscore, bpos = ascore, apos.copy()
        ascore, apos = s, wolves[i].copy()

      elif s < bscore:
        dscore, dpos = bscore, bpos.copy()
        bscore, bpos = s, wolves[i].copy()

      elif s < dscore:
        dscore, dpos = s, wolves[i].copy()

    history.append(ascore)
    a = 2.0 - t * (2.0 / max_iter)  # Linearly decrease a from 2 to 0

    # Update wolf positions using α, β, δ guidance
    for i in range(n_wolves):
      new = np.zeros(n_feat)
      for j in range(n_feat):
        r1, r2 = random.random(), random.random()
        X1 = apos[j] - (2*a*r1 - a) * abs(2*r2*apos[j] - wolves[i][j])
        r1, r2 = random.random(), random.random()
        X2 = bpos[j] - (2*a*r1 - a) * abs(2*r2*bpos[j] - wolves[i][j])
        r1, r2 = random.random(), random.random()
        X3 = dpos[j] - (2*a*r1 - a) * abs(2*r2*dpos[j] - wolves[i][j])
        new[j] = (X1 + X2 + X3) / 3
      wolves[i] = np.clip(new, 0, 1)

    print(f'  GWO-FS {t+1:3d}/{max_iter} | cost={ascore:.4f} | feat={(apos>GWO_FS_THRESH).sum()}')
  return np.where(apos > GWO_FS_THRESH)[0], history

print(f'GWO Feature Selection | wolves={GWO_FS_WOLVES} iters={GWO_FS_ITER} cv=StratifiedKFold({GWO_FS_CV})')
selected_idx, fs_history = gwo_feature_selection(X_train_full, y_train_full)
selected_names = [feature_names[i] for i in selected_idx]
X_train_sel = X_train_full[:, selected_idx]
X_test_sel = X_test[:, selected_idx]
print(f'\nSelected {len(selected_idx)}/{n_features} features: {selected_names}')

plt.figure(figsize=(8, 4))
plt.plot(range(1, len(fs_history)+1), fs_history, 'o-', color='darkorange', markersize=4)
plt.xlabel('Iteration')
plt.ylabel('Best Cost')
plt.title('GWO Feature Selection — Convergence (Training Set)')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('gwo_fs_convergence.png', bbox_inches='tight')
plt.show()

# ================================================================
# CELL 5.5 — Feature Selection Stability Analysis
# ================================================================

print('\n' + '='*70)
print('  FEATURE SELECTION STABILITY ANALYSIS')
print('='*70)
selected_features_runs = []
n_stability_runs = 5

for run in range(n_stability_runs):
  np.random.seed(SEED + run * 1000)
  random.seed(SEED + run * 1000)
  sel_idx_run, _ = gwo_feature_selection(X_train_full, y_train_full)
  selected_features_runs.append(set(sel_idx_run))
  print(f'Run {run+1}: Selected {len(sel_idx_run)} features')

# Compute intersection (features selected in ALL runs)
common_features = selected_features_runs[0].intersection(*selected_features_runs[1:])
union_features = selected_features_runs[0].union(*selected_features_runs[1:])

stability_pct = len(common_features) / len(union_features) * 100
consistency_pct = len(common_features) / len(selected_idx) * 100

print(f'\nStability Metrics:')
print(f'  Features in all {n_stability_runs} runs: {len(common_features)} / {len(union_features)} = {stability_pct:.1f}%')
print(f'  Consistency vs main run: {len(common_features)} / {len(selected_idx)} = {consistency_pct:.1f}%')
print(f'  Union of all runs: {len(union_features)} features')

# Identify stable vs unstable features
stable_feats = [feature_names[i] for i in common_features]
unstable_feats = [feature_names[i] for i in union_features - common_features]

print(f'\nStable features (selected in all runs):')
for f in sorted(stable_feats):
    print(f'  - {f}')

if unstable_feats:
    print(f'\nUnstable features (not in all runs):')
    for f in sorted(unstable_feats)[:10]:  # Show top 10
        print(f'  - {f}')
    if len(unstable_feats) > 10:
        print(f'  ... and {len(unstable_feats)-10} more')

print(f'\nInterpretation: {"High stability" if stability_pct > 70 else "Moderate stability" if stability_pct > 50 else "Low stability"}')
print('='*70 + '\n')

# ================================================================
# CELL 6 — GWO Hyperparameter Tuning
# ================================================================

GWO_HP_WOLVES = 30
GWO_HP_ITER   = 100
GWO_HP_CV     = 5

HP_BOUNDS = np.array([
    [0.01, 0.3],   # learning_rate
    [2,    4   ],   # max_depth
    [50,   200 ],   # n_estimators
    [0.5,  1.0 ],   # subsample
    [0.5,  1.0 ],   # colsample_bytree
    [3,    10  ],   # min_child_weight
    [0,    5   ],   # gamma
    [1, 8], #reg alpha
    [1, 10] # reg lambda

])

def decode_hp(pos):
  return {
      'learning_rate':    float(np.clip(pos[0], *HP_BOUNDS[0])),
      'max_depth':        int(round(np.clip(pos[1], *HP_BOUNDS[1]))),
      'n_estimators':     int(round(np.clip(pos[2], *HP_BOUNDS[2]))),
      'subsample':        float(np.clip(pos[3], *HP_BOUNDS[3])),
      'colsample_bytree': float(np.clip(pos[4], *HP_BOUNDS[4])),
      'min_child_weight': int(round(np.clip(pos[5], *HP_BOUNDS[5]))),
      'gamma':            float(np.clip(pos[6], *HP_BOUNDS[6])),
      'reg_alpha':        float(np.clip(pos[7], *HP_BOUNDS[7])),
      'reg_lambda':       float(np.clip(pos[8], *HP_BOUNDS[8])),
      }

def fitness_hp(pos, X, y):
  hp = decode_hp(pos)
  obj = 'binary:logistic' if n_classes == 2 else 'multi:softmax'
  clf = xgb.XGBClassifier(**hp, objective=obj, eval_metric='logloss',
                            tree_method='hist', random_state=SEED)
  pipe = Pipeline([('sc', RobustScaler()), ('clf', clf)])
  cv = StratifiedKFold(n_splits=GWO_HP_CV, shuffle=True, random_state=SEED)
  return 1.0 - cross_val_score(pipe, X, y, cv=cv, scoring='accuracy', n_jobs=-1).mean()

def gwo_hyperparameter_tuning(X, y, bounds=HP_BOUNDS, n_wolves=GWO_HP_WOLVES, max_iter=GWO_HP_ITER):
  dim = bounds.shape[0]
  wolves = bounds[:, 0] + np.random.rand(n_wolves, dim) * (bounds[:, 1] - bounds[:, 0])
  apos, ascore = np.zeros(dim), float('inf')
  bpos, bscore = np.zeros(dim), float('inf')
  dpos, dscore = np.zeros(dim), float('inf')
  history = []

  for t in range(max_iter):
      for i in range(n_wolves):
          s = fitness_hp(wolves[i], X, y)
          if s < ascore:
              dscore, dpos = bscore, bpos.copy()
              bscore, bpos = ascore, apos.copy()
              ascore, apos = s, wolves[i].copy()
          elif s < bscore:
              dscore, dpos = bscore, bpos.copy()
              bscore, bpos = s, wolves[i].copy()
          elif s < dscore:
              dscore, dpos = s, wolves[i].copy()

      history.append(ascore)
      a = 2.0 - t * (2.0 / max_iter)

      for i in range(n_wolves):
          new = np.zeros(dim)
          for j in range(dim):
              r1, r2 = random.random(), random.random()
              X1 = apos[j] - (2*a*r1 - a) * abs(2*r2*apos[j] - wolves[i][j])
              r1, r2 = random.random(), random.random()
              X2 = bpos[j] - (2*a*r1 - a) * abs(2*r2*bpos[j] - wolves[i][j])
              r1, r2 = random.random(), random.random()
              X3 = dpos[j] - (2*a*r1 - a) * abs(2*r2*dpos[j] - wolves[i][j])
              new[j] = (X1 + X2 + X3) / 3
          wolves[i] = np.clip(new, bounds[:, 0], bounds[:, 1])

      print(f'  GWO-HP {t+1:3d}/{max_iter} | best CV acc={(1-ascore)*100:.2f}%')
  return decode_hp(apos), ascore, history

print(f'GWO Hyperparameter Tuning | wolves={GWO_HP_WOLVES} iters={GWO_HP_ITER} cv=StratifiedKFold({GWO_HP_CV})')
best_hp, best_hp_cost, hp_history = gwo_hyperparameter_tuning(X_train_sel, y_train_full)
print('\nBest HP:', best_hp)
print(f'Best CV Accuracy: {(1-best_hp_cost)*100:.2f}%')

plt.figure(figsize=(8, 4))
plt.plot(range(1, len(hp_history)+1), [1-c for c in hp_history], 's-', color='steelblue', markersize=4)
plt.xlabel('Iteration')
plt.ylabel('Best CV Accuracy')
plt.title('GWO Hyperparameter Tuning — Convergence (Training Set)')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('gwo_hp_convergence.png', bbox_inches='tight')
plt.show()

# ================================================================
# CELL 7 — Final Evaluation: 5-Fold CV on Training Set + Independent Test Set
# ================================================================

OUTER_FOLDS = 5
outer_cv = StratifiedKFold(n_splits=OUTER_FOLDS, shuffle=True, random_state=SEED)
fold_results = {
    'fold': [], 'train_accuracy': [], 'accuracy': [], 'f1_macro': [], 'roc_auc': [],
    'sensitivity': [], 'specificity': [], 'mcc': [], 'kappa': []
}
all_y_true_cv, all_y_pred_cv, all_y_prob_cv = [], [], []

print(f'{OUTER_FOLDS}-fold StratifiedKFold (Train Set) | {X_train_sel.shape[0]} subjects | ~{X_train_sel.shape[0]//OUTER_FOLDS} per fold\n')

for fold_i, (tr_idx, te_idx) in enumerate(outer_cv.split(X_train_sel, y_train_full), 1):
    X_tr, X_te = X_train_sel[tr_idx], X_train_sel[te_idx]
    y_tr, y_te = y_train_full[tr_idx], y_train_full[te_idx]

    sc = RobustScaler()
    X_tr_sc = sc.fit_transform(X_tr)
    X_te_sc = sc.transform(X_te)

    if USE_SMOTE:
        X_tr_sc, y_tr = SMOTE(random_state=SEED).fit_resample(X_tr_sc, y_tr)

    obj = 'binary:logistic' if n_classes == 2 else 'multi:softmax'
    model = xgb.XGBClassifier(**best_hp, objective=obj, eval_metric='logloss',
                              tree_method='hist', random_state=SEED)
    model.fit(X_tr_sc, y_tr)

    tr_acc = accuracy_score(y_tr, model.predict(X_tr_sc))
    y_pred = model.predict(X_te_sc)
    y_prob = model.predict_proba(X_te_sc)

    acc = accuracy_score(y_te, y_pred)
    f1 = f1_score(y_te, y_pred, average='macro')
    auc = (roc_auc_score(y_te, y_prob[:, 1]) if n_classes == 2
           else roc_auc_score(y_te, y_prob, multi_class='ovr', average='macro'))

    # Class-wise metrics
    prec, recall, _, _ = precision_recall_fscore_support(y_te, y_pred, average=None, labels=[0, 1])
    sensitivity = recall[1] if n_classes == 2 else recall[1]  # ASD recall
    specificity = recall[0] if n_classes == 2 else recall[0]  # Control recall
    mcc = matthews_corrcoef(y_te, y_pred)
    kappa = cohen_kappa_score(y_te, y_pred)

    fold_results['fold'].append(fold_i)
    fold_results['train_accuracy'].append(tr_acc)
    fold_results['accuracy'].append(acc)
    fold_results['f1_macro'].append(f1)
    fold_results['roc_auc'].append(auc)
    fold_results['sensitivity'].append(sensitivity)
    fold_results['specificity'].append(specificity)
    fold_results['mcc'].append(mcc)
    fold_results['kappa'].append(kappa)
    all_y_true_cv.extend(y_te)
    all_y_pred_cv.extend(y_pred)
    all_y_prob_cv.extend(y_prob.tolist())

    print(f'  Fold {fold_i}: Train={tr_acc*100:.1f}%  CV Test={acc*100:.1f}%  '
          f'Gap={(tr_acc-acc)*100:.1f}%  Sens={sensitivity*100:.1f}%  Spec={specificity*100:.1f}%')

all_y_true_cv = np.array(all_y_true_cv)
all_y_pred_cv = np.array(all_y_pred_cv)
all_y_prob_cv = np.array(all_y_prob_cv)

mt_cv = np.mean(fold_results['train_accuracy'])
mv_cv = np.mean(fold_results['accuracy'])
gap_cv = (mt_cv - mv_cv) * 100

# ===== INDEPENDENT TEST SET EVALUATION =====
print(f'\n{"="*70}')
print('  INDEPENDENT TEST SET EVALUATION (Never Seen During Training)')
print(f'{"="*70}')
sc_final = RobustScaler()
X_train_sel_sc = sc_final.fit_transform(X_train_sel)
X_test_sc = sc_final.transform(X_test_sel)

if USE_SMOTE:
    X_train_sel_sc_smote, y_train_full_smote = SMOTE(random_state=SEED).fit_resample(
        X_train_sel_sc, y_train_full
    )
else:
    X_train_sel_sc_smote, y_train_full_smote = X_train_sel_sc, y_train_full

obj = 'binary:logistic' if n_classes == 2 else 'multi:softmax'
final_test_model = xgb.XGBClassifier(**best_hp, objective=obj, eval_metric='logloss',
                                      tree_method='hist', random_state=SEED)
final_test_model.fit(X_train_sel_sc_smote, y_train_full_smote)

y_test_pred = final_test_model.predict(X_test_sc)
y_test_prob = final_test_model.predict_proba(X_test_sc)

test_acc = accuracy_score(y_test, y_test_pred)
test_f1 = f1_score(y_test, y_test_pred, average='macro')
test_auc = (roc_auc_score(y_test, y_test_prob[:, 1]) if n_classes == 2
            else roc_auc_score(y_test, y_test_prob, multi_class='ovr', average='macro'))
test_prec, test_recall, _, _ = precision_recall_fscore_support(
    y_test, y_test_pred, average=None, labels=[0, 1]
)
test_sensitivity = test_recall[1]
test_specificity = test_recall[0]
test_mcc = matthews_corrcoef(y_test, y_test_pred)
test_kappa = cohen_kappa_score(y_test, y_test_pred)

print(f'\n  Test Accuracy   : {test_acc*100:.2f}%')
print(f'  Test F1-Macro   : {test_f1*100:.2f}%')
print(f'  Test Sensitivity: {test_sensitivity*100:.2f}%  (ASD Recall)')
print(f'  Test Specificity: {test_specificity*100:.2f}%  (Control Recall)')
print(f'  Test MCC        : {test_mcc:.4f}')
print(f'  Test Kappa      : {test_kappa:.4f}')
print(f'  Test ROC-AUC    : {test_auc:.4f}')

print(f'\n{"="*70}')
print('  5-FOLD CV RESULTS (Training Set)')
print(f'{"="*70}')
print(f'  CV Train Accuracy : {mt_cv*100:.2f}% ± {np.std(fold_results["train_accuracy"])*100:.2f}%')
print(f'  CV Test Accuracy  : {mv_cv*100:.2f}% ± {np.std(fold_results["accuracy"])*100:.2f}%')
status = 'Overfitting' if gap_cv > 15 else 'Mild overfit' if gap_cv > 7 else 'Good'
print(f'  Train-Test Gap    : {gap_cv:.2f}%  {status}')
print(f'  CV Sensitivity    : {np.mean(fold_results["sensitivity"])*100:.2f}%')
print(f'  CV Specificity    : {np.mean(fold_results["specificity"])*100:.2f}%')
print(f'  CV F1-Macro       : {np.mean(fold_results["f1_macro"])*100:.2f}%')
print(f'  CV MCC            : {np.mean(fold_results["mcc"]):.4f}')
print(f'  CV Cohen\'s Kappa  : {np.mean(fold_results["kappa"]):.4f}')
print(f'  CV ROC-AUC        : {np.mean(fold_results["roc_auc"]):.4f} ± {np.std(fold_results["roc_auc"]):.4f}')
print(f'{"="*70}')
print('\nClassification Report (CV Predictions):')
print(classification_report(all_y_true_cv, all_y_pred_cv, target_names=le.classes_))
print('\nClassification Report (Independent Test Set):')
print(classification_report(y_test, y_test_pred, target_names=le.classes_))

# ================================================================
# CELL 7.5 — Detailed Per-Class Metrics (CV and Test Set)
# ================================================================

print('='*70)
print('  DETAILED PER-CLASS METRICS (CV Predictions)')
print('='*70)
prec_cv, recall_cv, f1_cv, _ = precision_recall_fscore_support(
    all_y_true_cv, all_y_pred_cv, labels=[0, 1], average=None
)
print(f'\nControl Class (Label=0):')
print(f'  Precision : {prec_cv[0]*100:.2f}%  (of predicted Control, {prec_cv[0]*100:.1f}% correct)')
print(f'  Recall    : {recall_cv[0]*100:.2f}%  (of actual Control, caught {recall_cv[0]*100:.1f}%)')
print(f'  F1-Score  : {f1_cv[0]:.4f}')

print(f'\nASD Class (Label=1):')
print(f'  Precision : {prec_cv[1]*100:.2f}%  (of predicted ASD, {prec_cv[1]*100:.1f}% correct)')
print(f'  Recall    : {recall_cv[1]*100:.2f}%  (of actual ASD, caught {recall_cv[1]*100:.1f}%)')
print(f'  F1-Score  : {f1_cv[1]:.4f}')

print(f'\n--- DETAILED PER-CLASS METRICS (Independent Test Set) ---')
prec_test, recall_test, f1_test, _ = precision_recall_fscore_support(
    y_test, y_test_pred, labels=[0, 1], average=None
)
print(f'\nControl Class (Label=0):')
print(f'  Precision : {prec_test[0]*100:.2f}%')
print(f'  Recall    : {recall_test[0]*100:.2f}%')
print(f'  F1-Score  : {f1_test[0]:.4f}')

print(f'\nASD Class (Label=1):')
print(f'  Precision : {prec_test[1]*100:.2f}%')
print(f'  Recall    : {recall_test[1]*100:.2f}%')
print(f'  F1-Score  : {f1_test[1]:.4f}')
print('='*70)

# ================================================================
# CELL 7.6 - Permutation Test
# ================================================================

from sklearn.model_selection import permutation_test_score

print('='*70)
print('  STATISTICAL VALIDATION')
print('='*70)

# ----------------------------------------------------------------
#  PERMUTATION TEST (GWO-Optimized Model)
# ----------------------------------------------------------------

print('\n' + '-'*70)
print('  PART 1: Permutation Test (GWO-XGBoost Model)')
print('-'*70)
print('  Null Hypothesis: Features and labels are independent')
print('  (i.e., model performance is due to chance)')
print(f'  Running 1000 permutations with 5-fold Stratified CV...')
print('  (This may take several minutes)\n')

# Build the final pipeline with GWO-selected features and tuned HP
obj = 'binary:logistic' if n_classes == 2 else 'multi:softmax'
perm_model = Pipeline([
    ('sc', RobustScaler()),
    ('clf', xgb.XGBClassifier(
        **best_hp,
        objective=obj,
        eval_metric='logloss',
        tree_method='hist',
        random_state=SEED
    ))
])

perm_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

# Run permutation test on TRAINING SET with GWO-selected features
score_gwo, perm_scores_gwo, pvalue_gwo = permutation_test_score(
    estimator=perm_model,
    X=X_train_sel,           # GWO-selected features
    y=y_train_full,
    cv=perm_cv,
    n_permutations=1000,
    scoring='accuracy',
    random_state=SEED,
    n_jobs=-1
)

print(f'  Results (GWO-XGBoost, 13 features):')
print(f'    True CV Accuracy:        {score_gwo*100:.2f}%')
print(f'    Permutation Mean ± SD:   {perm_scores_gwo.mean()*100:.2f}% ± {perm_scores_gwo.std()*100:.2f}%')
print(f'    p-value:                 {pvalue_gwo:.4f}')
print(f'    Significant (p < 0.05):  {"YES ✓" if pvalue_gwo < 0.05 else "NO ✗"}')
print(f'    Significant (p < 0.01):  {"YES ✓" if pvalue_gwo < 0.01 else "NO ✗"}')

# ----------------------------------------------------------------
# Permutation Test (Baseline Model — All 79 Features)
# ----------------------------------------------------------------

print('\n' + '-'*70)
print('  PART 1b: Permutation Test (Baseline XGBoost, All 79 Features)')
print('-'*70)

perm_model_baseline = Pipeline([
    ('sc', RobustScaler()),
    ('clf', xgb.XGBClassifier(
        n_estimators=100, max_depth=3, learning_rate=0.1,
        eval_metric='logloss', tree_method='hist', random_state=SEED
    ))
])

score_base, perm_scores_base, pvalue_base = permutation_test_score(
    estimator=perm_model_baseline,
    X=X_train_full,          # All 79 features
    y=y_train_full,
    cv=perm_cv,
    n_permutations=1000,
    scoring='accuracy',
    random_state=SEED,
    n_jobs=-1
)

print(f'  Results (Baseline XGBoost, 79 features):')
print(f'    True CV Accuracy:        {score_base*100:.2f}%')
print(f'    Permutation Mean ± SD:   {perm_scores_base.mean()*100:.2f}% ± {perm_scores_base.std()*100:.2f}%')
print(f'    p-value:                 {pvalue_base:.4f}')
print(f'    Significant (p < 0.05):  {"YES ✓" if pvalue_base < 0.05 else "NO ✗"}')

# ----------------------------------------------------------------
# VISUALIZATION PART
# ----------------------------------------------------------------

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Statistical Validation of Model Performance', fontweight='bold')

# Plot 1: Permutation test distribution (GWO model)
ax = axes[0]
ax.hist(perm_scores_gwo, bins=30, color='lightcoral', edgecolor='white',
        alpha=0.8, density=True, label='Permuted scores')
ax.axvline(score_gwo, color='darkred', linewidth=2.5, linestyle='-',
           label=f'True score = {score_gwo*100:.1f}%')
ax.axvline(0.5, color='grey', linewidth=1, linestyle=':', label='Chance (50%)')
ax.set_xlabel('Accuracy')
ax.set_ylabel('Density')
ax.set_title(f'Permutation Test (GWO-XGBoost)\np = {pvalue_gwo:.4f}')
ax.legend(fontsize=9)
ax.grid(alpha=0.3)

# Add annotation for p-value interpretation
significance_text = "Significant (p < 0.05)" if pvalue_gwo < 0.05 else "Not Significant"
color = 'green' if pvalue_gwo < 0.05 else 'red'
ax.text(0.05, 0.95, significance_text, transform=ax.transAxes,
        fontsize=10, verticalalignment='top', color=color, fontweight='bold')

# Plot 2: Permutation test distribution (Baseline)
ax = axes[1]
ax.hist(perm_scores_base, bins=30, color='lightblue', edgecolor='white',
        alpha=0.8, density=True, label='Permuted scores')
ax.axvline(score_base, color='darkblue', linewidth=2.5, linestyle='-',
           label=f'True score = {score_base*100:.1f}%')
ax.axvline(0.5, color='grey', linewidth=1, linestyle=':', label='Chance (50%)')
ax.set_xlabel('Accuracy')
ax.set_ylabel('Density')
ax.set_title(f'Permutation Test (Baseline)\np = {pvalue_base:.4f}')
ax.legend(fontsize=9)
ax.grid(alpha=0.3)

significance_text = "Significant (p < 0.05)" if pvalue_base < 0.05 else "Not Significant"
color = 'green' if pvalue_base < 0.05 else 'red'
ax.text(0.05, 0.95, significance_text, transform=ax.transAxes,
        fontsize=10, verticalalignment='top', color=color, fontweight='bold')



plt.tight_layout()
plt.savefig('statistical_validation.png', bbox_inches='tight', dpi=150)
plt.show()

# ----------------------------------------------------------------
# PART 4: SUMMARY TABLE FOR THESIS
# ----------------------------------------------------------------

print('\n' + '='*70)
print('  SUMMARY TABLE FOR THESIS (Chapter IV)')
print('='*70)
print(f'''
  ┌─────────────────────────────────────────────────────────────────┐
  │  Statistical Validation Results                                  │
  ├─────────────────────────────────────────────────────────────────┤
  │  Test                          │ Result      │ Interpretation    │
  ├────────────────────────────────┼─────────────┼───────────────────┤
  │  Permutation Test (GWO model)  │ p = {pvalue_gwo:.4f}  │ {"Significant ✓" if pvalue_gwo < 0.05 else "Not Sig. ✗   "}   │
  │  Permutation Test (Baseline)   │ p = {pvalue_base:.4f}  │ {"Significant ✓" if pvalue_base < 0.05 else "Not Sig. ✗   "}   │
  └────────────────────────────────┴─────────────┴───────────────────┘

  Interpretation:
  - Permutation test p < 0.05 confirms model learned genuine patterns
    from EEG features (not random chance)
  - Paired tests compare improvement across identical CV folds
''')

# Save results
stat_results = pd.DataFrame({
    'Test': ['Permutation (GWO-XGBoost)', 'Permutation (Baseline)'],
    'Statistic': [f'score={score_gwo:.4f}', f'score={score_base:.4f}'],
    'p-value': [pvalue_gwo, pvalue_base],
    'Significant (α=0.05)': [pvalue_gwo < 0.05, pvalue_base < 0.05],
    'n_permutations / n_pairs': [1000, 1000]
})
stat_results.to_csv('statistical_validation_results.csv', index=False)
print('  Results saved to: statistical_validation_results.csv')
print('='*70)

# ================================================================
# CELL 8 — Overfitting Diagnostic Plots (CV on Training Set)
# ================================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Overfitting Diagnostic — 5-Fold CV on Training Set (n=45)', fontweight='bold')

folds = fold_results['fold']
tr_accs = [v*100 for v in fold_results['train_accuracy']]
te_accs = [v*100 for v in fold_results['accuracy']]
gaps_plot = [tr-te for tr, te in zip(tr_accs, te_accs)]

ax = axes[0]
x = np.arange(len(folds))
ax.bar(x-0.2, tr_accs, 0.4, label='Train', color='steelblue', alpha=0.85)
ax.bar(x+0.2, te_accs, 0.4, label='CV Test', color='tomato', alpha=0.85)
ax.axhline(np.mean(tr_accs), color='steelblue', linestyle='--', lw=1.5, label=f'Train Mean={np.mean(tr_accs):.1f}%')
ax.axhline(np.mean(te_accs), color='tomato', linestyle='--', lw=1.5, label=f'CV Test Mean={np.mean(te_accs):.1f}%')
ax.set_xticks(x)
ax.set_xticklabels([f'F{f}' for f in folds])
ax.set_ylabel('Accuracy (%)')
ax.set_title('Per-Fold: Train vs CV Test')
ax.set_ylim([0, 110])
ax.legend(fontsize=8)
ax.grid(alpha=0.3, axis='y')

ax = axes[1]
colors = ['tomato' if g > 15 else 'orange' if g > 7 else 'mediumseagreen' for g in gaps_plot]
ax.bar(folds, gaps_plot, color=colors, edgecolor='white')
ax.axhline(7, color='orange', linestyle=':', lw=1.5, label='7% (mild)')
ax.axhline(15, color='tomato', linestyle=':', lw=1.5, label='15% (high)')
ax.set_xlabel('Fold')
ax.set_ylabel('Train − CV Test (%)')
ax.set_title('Overfitting Gap per Fold')
ax.legend(fontsize=8)
ax.grid(alpha=0.3, axis='y')
for f, g in zip(folds, gaps_plot):
    ax.text(f, g+0.3, f'{g:.1f}%', ha='center', fontsize=9)

ax = axes[2]
ax.scatter(tr_accs, te_accs, color='steelblue', s=90, zorder=5)
for tr, te, f in zip(tr_accs, te_accs, folds):
    ax.annotate(f'F{f}', (tr, te), textcoords='offset points', xytext=(5, 4), fontsize=9)
lo = min(min(tr_accs), min(te_accs)) - 5
hi = max(max(tr_accs), max(te_accs)) + 5
ax.plot([lo, hi], [lo, hi], 'k--', lw=1.5, label='No overfit')
ax.set_xlabel('Train Accuracy (%)')
ax.set_ylabel('CV Test Accuracy (%)')
ax.set_title('Scatter (below diagonal = overfit)')
ax.legend(fontsize=8)
ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('overfitting_diagnostic.png', bbox_inches='tight')
plt.show()

# ================================================================
# CELL 9 — Evaluation Plots: CV and Independent Test Set
# ================================================================
fig, axes = plt.subplots(2, 3, figsize=(20, 10))

# Row 1: CV Results
ax = axes[0, 0]
cm_cv = confusion_matrix(all_y_true_cv, all_y_pred_cv)
cm_pct_cv = cm_cv.astype(float) / cm_cv.sum(axis=1, keepdims=True) * 100
annot_cv = [[f'{v}\n({p:.1f}%)' for v, p in zip(rv, rp)] for rv, rp in zip(cm_cv, cm_pct_cv)]
sns.heatmap(cm_cv, annot=annot_cv, fmt='', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_, ax=ax, cbar=False)
ax.set_title('Confusion Matrix (CV Predictions)')
ax.set_xlabel('Predicted')
ax.set_ylabel('True')

ax = axes[0, 1]
if n_classes == 2:
    fpr_cv, tpr_cv, _ = roc_curve(all_y_true_cv, all_y_prob_cv[:, 1])
    auc_val_cv = roc_auc_score(all_y_true_cv, all_y_prob_cv[:, 1])
    ax.plot(fpr_cv, tpr_cv, color='steelblue', lw=2, label=f'AUC={auc_val_cv:.3f}')
    ax.plot([0, 1], [0, 1], '--', color='grey', lw=1)
    ax.set_xlabel('FPR')
    ax.set_ylabel('TPR')
    ax.set_title('ROC Curve (CV Predictions)')
    ax.legend(loc='lower right')
    ax.grid(alpha=0.3)

ax = axes[0, 2]
bars = ax.bar(fold_results['fold'], [v*100 for v in fold_results['accuracy']],
              color='mediumseagreen', edgecolor='white')
ax.axhline(mv_cv*100, color='red', linestyle='--', lw=1.5, label=f'Mean={mv_cv*100:.2f}%')
ax.axhline(80, color='orange', linestyle=':', lw=1.5, label='80% target')
ax.set_xlabel('Fold')
ax.set_ylabel('CV Test Accuracy (%)')
ax.set_title('Per-Fold CV Test Accuracy')
ax.set_ylim([0, 110])
ax.legend()
for bar, v in zip(bars, fold_results['accuracy']):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1,
            f'{v*100:.1f}%', ha='center', fontsize=10)

# Row 2: Independent Test Set Results
ax = axes[1, 0]
cm_test = confusion_matrix(y_test, y_test_pred)
cm_pct_test = cm_test.astype(float) / cm_test.sum(axis=1, keepdims=True) * 100
annot_test = [[f'{v}\n({p:.1f}%)' for v, p in zip(rv, rp)] for rv, rp in zip(cm_test, cm_pct_test)]
sns.heatmap(cm_test, annot=annot_test, fmt='', cmap='Greens',
            xticklabels=le.classes_, yticklabels=le.classes_, ax=ax, cbar=False)
ax.set_title('Confusion Matrix (Independent Test Set)')
ax.set_xlabel('Predicted')
ax.set_ylabel('True')

ax = axes[1, 1]
if n_classes == 2:
    fpr_test, tpr_test, _ = roc_curve(y_test, y_test_prob[:, 1])
    auc_val_test = roc_auc_score(y_test, y_test_prob[:, 1])
    ax.plot(fpr_test, tpr_test, color='mediumseagreen', lw=2, label=f'AUC={auc_val_test:.3f}')
    ax.plot([0, 1], [0, 1], '--', color='grey', lw=1)
    ax.set_xlabel('FPR')
    ax.set_ylabel('TPR')
    ax.set_title('ROC Curve (Independent Test Set)')
    ax.legend(loc='lower right')
    ax.grid(alpha=0.3)

ax = axes[1, 2]
metrics_names = ['Accuracy', 'Sensitivity', 'Specificity', 'F1-Macro', 'AUC']
cv_metrics = [
    mv_cv*100, np.mean(fold_results['sensitivity'])*100,
    np.mean(fold_results['specificity'])*100, np.mean(fold_results['f1_macro'])*100,
    np.mean(fold_results['roc_auc'])*100
]
test_metrics = [test_acc*100, test_sensitivity*100, test_specificity*100, test_f1*100, test_auc*100]

x_pos = np.arange(len(metrics_names))
width = 0.35
ax.bar(x_pos - width/2, cv_metrics, width, label='CV (Train Set)', color='steelblue', alpha=0.8)
ax.bar(x_pos + width/2, test_metrics, width, label='Test Set', color='mediumseagreen', alpha=0.8)
ax.set_ylabel('Score (%)')
ax.set_title('CV vs Independent Test Set Comparison')
ax.set_xticks(x_pos)
ax.set_xticklabels(metrics_names, rotation=45, ha='right', fontsize=9)
ax.set_ylim([0, 110])
ax.legend()
ax.grid(alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('evaluation_results.png', bbox_inches='tight')
plt.show()

# ================================================================
# CELL 10 — Learning Curve (Training Set Only)
# ================================================================

obj = 'binary:logistic' if n_classes == 2 else 'multi:softmax'
lc_pipe = Pipeline([
    ('sc', RobustScaler()),
    ('clf', xgb.XGBClassifier(**best_hp, objective=obj,
                              eval_metric='logloss', tree_method='hist', random_state=SEED))
])
lc_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

ts, tr_sc, te_sc = learning_curve(
    lc_pipe, X_train_sel, y_train_full, cv=lc_cv,
    train_sizes=np.linspace(0.2, 1.0, 8),
    scoring='accuracy', n_jobs=-1
)

plt.figure(figsize=(8, 5))
plt.plot(ts, tr_sc.mean(axis=1)*100, 'o-', color='steelblue', label='Training Accuracy')
plt.fill_between(ts, (tr_sc.mean(1)-tr_sc.std(1))*100,
                 (tr_sc.mean(1)+tr_sc.std(1))*100, alpha=0.15, color='steelblue')
plt.plot(ts, te_sc.mean(axis=1)*100, 'o-', color='tomato', label='CV Accuracy')
plt.fill_between(ts, (te_sc.mean(1)-te_sc.std(1))*100,
                 (te_sc.mean(1)+te_sc.std(1))*100, alpha=0.15, color='tomato')
plt.xlabel('Training Set Size (subjects)')
plt.ylabel('Accuracy (%)')
plt.title('Learning Curve — XGBoost+GWO (Training Set, n=45)')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('learning_curve.png', bbox_inches='tight')
plt.show()

# ================================================================
# CELL 11 — Final Model for SHAP (Trained on Full Training Set)
# ================================================================

scaler_shap = RobustScaler()
X_train_sel_scaled = scaler_shap.fit_transform(X_train_sel)
X_fit_shap, y_fit_shap = (
    SMOTE(random_state=SEED).fit_resample(X_train_sel_scaled, y_train_full)
    if USE_SMOTE else (X_train_sel_scaled, y_train_full)
)

obj = 'binary:logistic' if n_classes == 2 else 'multi:softmax'
final_model_shap = xgb.XGBClassifier(**best_hp, objective=obj,
                                      eval_metric='logloss', tree_method='hist', random_state=SEED)
final_model_shap.fit(X_fit_shap, y_fit_shap)

# ================================================================
# CELL 12 — SHAP Interpretability (Training Set)
# ================================================================

explainer = shap.TreeExplainer(final_model_shap)
shap_values = explainer.shap_values(X_train_sel_scaled)
sv = shap_values if (isinstance(shap_values, np.ndarray) and shap_values.ndim == 2) else shap_values[1]

plt.figure(figsize=(10, 7))
shap.summary_plot(sv, X_train_sel_scaled, feature_names=selected_names, show=False, plot_size=(10, 7))
plt.title('SHAP Beeswarm Plot — ASD Classification')
plt.tight_layout()
plt.savefig('shap_beeswarm.png', bbox_inches='tight')
plt.show()

mean_abs_shap = np.abs(sv).mean(axis=0)
order = np.argsort(mean_abs_shap)[::-1]
top_n = min(20, len(selected_names))
plt.figure(figsize=(9, 6))
plt.barh([selected_names[i] for i in order[:top_n]][::-1],
         mean_abs_shap[order[:top_n]][::-1], color='steelblue')
plt.xlabel('Mean |SHAP value|')
plt.title(f'Top {top_n} Features by SHAP Importance')
plt.tight_layout()
plt.savefig('shap_bar.png', bbox_inches='tight')
plt.show()

shap_df = pd.DataFrame({'Feature': selected_names, 'Mean_Abs_SHAP': mean_abs_shap})\
           .sort_values('Mean_Abs_SHAP', ascending=False)
shap_df.to_csv('shap_feature_importance.csv', index=False)
print('Top 10 SHAP Features:')
print(shap_df.head(10))

# ================================================================
# CELL 13 — Baseline Comparison
# ================================================================

baselines = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=SEED),
    'SVM (RBF)':           SVC(kernel='rbf', probability=True, random_state=SEED),
    'Random Forest':       RandomForestClassifier(n_estimators=200, random_state=SEED, n_jobs=-1),
    'Gradient Boosting':   GradientBoostingClassifier(n_estimators=200, random_state=SEED),
    'k-NN (k=5)':          KNeighborsClassifier(n_neighbors=5),
    'XGBoost (default)':   xgb.XGBClassifier(n_estimators=100, max_depth=3,
                                             learning_rate=0.1, eval_metric='logloss',
                                             random_state=SEED, tree_method='hist'),
}

cv_baseline = StratifiedKFold(n_splits=OUTER_FOLDS, shuffle=True, random_state=SEED)
auc_scoring = 'roc_auc' if n_classes == 2 else 'roc_auc_ovr_weighted'

# Storage for results
comparison_results_all_feat = {}  # On all 79 features
comparison_results_gwo_feat = {}  # On GWO-selected features

print('='*80)
print('BASELINE 1: Trained on ALL ORIGINAL FEATURES (79 features after variance filter)')
print('='*80)
print()
for name, clf in baselines.items():
    pipe = Pipeline([('sc', RobustScaler()), ('clf', clf)])
    acc = cross_val_score(pipe, X_train_full, y_train_full, cv=cv_baseline, scoring='accuracy', n_jobs=-1)
    f1 = cross_val_score(pipe, X_train_full, y_train_full, cv=cv_baseline, scoring='f1_macro', n_jobs=-1)
    auc = cross_val_score(pipe, X_train_full, y_train_full, cv=cv_baseline, scoring=auc_scoring, n_jobs=-1)
    comparison_results_all_feat[name] = {
        'acc_mean': acc.mean(), 'acc_std': acc.std(),
        'f1_mean': f1.mean(), 'auc_mean': auc.mean()
    }
    print(f'{name:35s} Acc={acc.mean()*100:.2f}±{acc.std()*100:.2f}% | F1={f1.mean()*100:.2f}% | AUC={auc.mean():.3f}')

print()
print('='*80)
print('BASELINE 2: Trained on GWO-SELECTED FEATURES (subset)')
print('='*80)
print()
for name, clf in baselines.items():
    pipe = Pipeline([('sc', RobustScaler()), ('clf', clf)])
    acc = cross_val_score(pipe, X_train_sel, y_train_full, cv=cv_baseline, scoring='accuracy', n_jobs=-1)
    f1 = cross_val_score(pipe, X_train_sel, y_train_full, cv=cv_baseline, scoring='f1_macro', n_jobs=-1)
    auc = cross_val_score(pipe, X_train_sel, y_train_full, cv=cv_baseline, scoring=auc_scoring, n_jobs=-1)
    comparison_results_gwo_feat[name] = {
        'acc_mean': acc.mean(), 'acc_std': acc.std(),
        'f1_mean': f1.mean(), 'auc_mean': auc.mean()
    }
    print(f'{name:35s} Acc={acc.mean()*100:.2f}±{acc.std()*100:.2f}% | F1={f1.mean()*100:.2f}% | AUC={auc.mean():.3f}')

print()
print('='*80)
print('BASELINE 3: Our Method — XGBoost + GWO Features + Tuned HP')
print('='*80)
print(f'{"XGBoost + GWO (ours)":35s} Acc={mv_cv*100:.2f}±{np.std(fold_results["accuracy"])*100:.2f}% | '
      f'F1={np.mean(fold_results["f1_macro"])*100:.2f}% | AUC={np.mean(fold_results["roc_auc"]):.3f}')

print()
print('='*80)
print('IMPACT ANALYSIS: Feature Selection Effect (GWO vs All Features)')
print('='*80)
print()
print(f'{"Model":35s} | {"All Features":18s} | {"GWO Features":18s} | {"Δ (GWO - All)":15s}')
print('-'*80)
for name in baselines.keys():
    all_acc = comparison_results_all_feat[name]['acc_mean'] * 100
    gwo_acc = comparison_results_gwo_feat[name]['acc_mean'] * 100
    delta = gwo_acc - all_acc
    symbol = '✓' if delta > 0 else '✗'
    print(f'{name:35s} | {all_acc:6.2f}%         | {gwo_acc:6.2f}%         | {delta:+6.2f}%  {symbol}')

# Combined results
comparison_results = {**comparison_results_gwo_feat}
comparison_results['XGBoost + GWO (ours)'] = {
    'acc_mean': mv_cv, 'acc_std': np.std(fold_results['accuracy']),
    'f1_mean': np.mean(fold_results['f1_macro']),
    'auc_mean': np.mean(fold_results['roc_auc']),
}

# Save comparison tables
comp_df_all = pd.DataFrame([{
    'Classifier': n,
    'Feature_Set': 'All (79)',
    'Accuracy (%)': f"{v['acc_mean']*100:.2f} ± {v['acc_std']*100:.2f}",
    'F1-Macro (%)': f"{v['f1_mean']*100:.2f}",
    'ROC-AUC': f"{v['auc_mean']:.4f}"
} for n, v in comparison_results_all_feat.items()])

comp_df_gwo = pd.DataFrame([{
    'Classifier': n,
    'Feature_Set': 'GWO-Selected',
    'Accuracy (%)': f"{v['acc_mean']*100:.2f} ± {v['acc_std']*100:.2f}",
    'F1-Macro (%)': f"{v['f1_mean']*100:.2f}",
    'ROC-AUC': f"{v['auc_mean']:.4f}"
} for n, v in comparison_results_gwo_feat.items()])

comp_df_combined = pd.concat([comp_df_all, comp_df_gwo], ignore_index=True)
comp_df_combined.to_csv('classifier_comparison_detailed.csv', index=False)
print(f'\nDetailed comparison saved to: classifier_comparison_detailed.csv')

# ================================================================
# Ablation Study: Component Importance
# ================================================================

print('\n' + '='*70)
print('  ABLATION STUDY: Component Contribution')
print('='*70)

cv_ablation = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

# 1. All features with default HP
print('\n1. XGBoost + All Features (default HP):')
pipe1 = Pipeline([
    ('sc', RobustScaler()),
    ('clf', xgb.XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1,
                              eval_metric='logloss', random_state=SEED, tree_method='hist'))
])
acc1 = cross_val_score(pipe1, X_train_full, y_train_full, cv=cv_ablation, scoring='accuracy', n_jobs=-1)
print(f'   Accuracy: {acc1.mean()*100:.2f}% ± {acc1.std()*100:.2f}%')

# 2. GWO features with default HP
print('\n2. XGBoost + GWO Features (default HP):')
pipe2 = Pipeline([
    ('sc', RobustScaler()),
    ('clf', xgb.XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1,
                              eval_metric='logloss', random_state=SEED, tree_method='hist'))
])
acc2 = cross_val_score(pipe2, X_train_sel, y_train_full, cv=cv_ablation, scoring='accuracy', n_jobs=-1)
print(f'   Accuracy: {acc2.mean()*100:.2f}% ± {acc2.std()*100:.2f}%')
print(f'   Δ vs (1): {(acc2.mean()-acc1.mean())*100:+.2f}% (feature selection impact)')

# 3. GWO features with tuned HP (full method)
print('\n3. XGBoost + GWO Features + Tuned HP (Full Method):')
print(f'   Accuracy: {mv_cv*100:.2f}% ± {np.std(fold_results["accuracy"])*100:.2f}%')
print(f'   Δ vs (2): {(mv_cv-acc2.mean())*100:+.2f}% (HP tuning impact)')
print(f'   Δ vs (1): {(mv_cv-acc1.mean())*100:+.2f}% (total improvement)')

improvement_features = (acc2.mean() - acc1.mean()) * 100
improvement_tuning = (mv_cv - acc2.mean()) * 100
total_improvement = (mv_cv - acc1.mean()) * 100

print(f'\n--- Summary ---')
print(f'  Feature Selection (GWO): {improvement_features:+.2f}%')
print(f'  HP Tuning (GWO):         {improvement_tuning:+.2f}%')
print(f'  Total Improvement:       {total_improvement:+.2f}%')
print('='*70)

# ================================================================
# Feature Domain Ablation Study
# ================================================================

print('\n' + '='*70)
print('  FEATURE DOMAIN ABLATION STUDY')
print('  Testing individual and combined domain contributions')
print('='*70)

# Define feature domains by name prefix

# Categorize all 79 features into their respective domains
spectral_feat_names = [f for f in feature_names if f.startswith('abs_') or
                       f.startswith('rel_') or
                       f in ['theta_alpha_F', 'theta_beta_F']]

connectivity_feat_names = [f for f in feature_names if f.startswith('coh_')]

entropy_feat_names = [f for f in feature_names if f.startswith('sampen_')]

# Get column indices for each domain
spectral_idx_domain = [feature_names.index(f) for f in spectral_feat_names]
connectivity_idx_domain = [feature_names.index(f) for f in connectivity_feat_names]
entropy_idx_domain = [feature_names.index(f) for f in entropy_feat_names]


ablation_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

# Default XGBoost
def make_default_xgb():
    return xgb.XGBClassifier(
        n_estimators=100, max_depth=3, learning_rate=0.1, eval_metric='logloss', random_state=SEED, tree_method='hist'
    )

# Define all experimental conditions
ablation_experiments = {
    # A) Single-domain experiments
    'A1: Spectral Only (42 feat)': spectral_idx_domain,
    'A2: Connectivity Only (32 feat)': connectivity_idx_domain,
    'A3: Entropy Only (5 feat)': entropy_idx_domain,

    # B) Dual-domain experiments
    'B1: Spectral + Connectivity (74 feat)': spectral_idx_domain + connectivity_idx_domain,
    'B2: Spectral + Entropy (47 feat)': spectral_idx_domain + entropy_idx_domain,
    'B3: Connectivity + Entropy (37 feat)': connectivity_idx_domain + entropy_idx_domain,

    # C) Full multi-domain (all 79 features)
    'C: All Domains (79 feat)': list(range(len(feature_names))),

    # D) GWO-selected features (13 features, default HP)
    'D: GWO-Selected (13 feat, default HP)': list(selected_idx),

    # E) GWO-selected + tuned HP (proposed method) — computed separately
}


print(f'\n  Running {len(ablation_experiments) + 1} experiments with 5-fold Stratified CV...')
print(f'  Training set: {X_train_full.shape[0]} subjects')
print(f'  {"─"*65}')
print(f'  {"Experiment":<45} {"Acc (%)":<18} {"F1 (%)":<10} {"AUC":<8}')
print(f'  {"─"*65}')

ablation_results = {}

for exp_name, feat_indices in ablation_experiments.items():
    # Extract domain-specific features from training set
    X_domain = X_train_full[:, feat_indices]

    # Create pipeline with RobustScaler + default XGBoost
    pipe = Pipeline([
        ('sc', RobustScaler()),
        ('clf', make_default_xgb())
    ])

    # Compute CV metrics
    acc_scores = cross_val_score(pipe, X_domain, y_train_full,
                                 cv=ablation_cv, scoring='accuracy', n_jobs=-1)
    f1_scores = cross_val_score(pipe, X_domain, y_train_full,
                                cv=ablation_cv, scoring='f1_macro', n_jobs=-1)
    auc_scores = cross_val_score(pipe, X_domain, y_train_full,
                                 cv=ablation_cv, scoring='roc_auc', n_jobs=-1)

    ablation_results[exp_name] = {
        'accuracy_mean': acc_scores.mean(),
        'accuracy_std': acc_scores.std(),
        'f1_mean': f1_scores.mean(),
        'f1_std': f1_scores.std(),
        'auc_mean': auc_scores.mean(),
        'auc_std': auc_scores.std(),
        'n_features': len(feat_indices),
        'fold_accuracies': acc_scores.tolist()
    }

    print(f'  {exp_name:<45} {acc_scores.mean()*100:.2f}±{acc_scores.std()*100:.2f}  '
          f'{f1_scores.mean()*100:.2f}     {auc_scores.mean():.3f}')

ablation_results['E: GWO + Tuned HP (13 feat, OURS)'] = {
    'accuracy_mean': mv_cv,
    'accuracy_std': np.std(fold_results['accuracy']),
    'f1_mean': np.mean(fold_results['f1_macro']),
    'f1_std': np.std(fold_results['f1_macro']),
    'auc_mean': np.mean(fold_results['roc_auc']),
    'auc_std': np.std(fold_results['roc_auc']),
    'n_features': len(selected_idx),
    'fold_accuracies': fold_results['accuracy']
}

print(f'  {"E: GWO + Tuned HP (13 feat, OURS)":<45} {mv_cv*100:.2f}±{np.std(fold_results["accuracy"])*100:.2f}  '
      f'{np.mean(fold_results["f1_macro"])*100:.2f}     {np.mean(fold_results["roc_auc"]):.3f}')
print(f'  {"─"*65}')


# ================================================================
# CELL 14 — Feature Selection Impact Visualization
# Shows side-by-side comparison: All Features vs GWO-Selected Features
# ================================================================

fig, axes = plt.subplots(2, 3, figsize=(20, 10))
fig.suptitle('Impact of GWO Feature Selection on Baseline Methods', fontweight='bold', fontsize=14)

# Extract data for visualization
clf_names_all = list(comparison_results_all_feat.keys())
acc_all = [comparison_results_all_feat[n]['acc_mean']*100 for n in clf_names_all]
acc_gwo = [comparison_results_gwo_feat[n]['acc_mean']*100 for n in clf_names_all]
acc_delta = [g - a for g, a in zip(acc_gwo, acc_all)]

f1_all = [comparison_results_all_feat[n]['f1_mean']*100 for n in clf_names_all]
f1_gwo = [comparison_results_gwo_feat[n]['f1_mean']*100 for n in clf_names_all]
f1_delta = [g - a for g, a in zip(f1_gwo, f1_all)]

auc_all = [comparison_results_all_feat[n]['auc_mean']*100 for n in clf_names_all]
auc_gwo = [comparison_results_gwo_feat[n]['auc_mean']*100 for n in clf_names_all]
auc_delta = [g - a for g, a in zip(auc_gwo, auc_all)]

x = np.arange(len(clf_names_all))
width = 0.35

# Row 1: Absolute performance comparison
for ax_idx, (vals_all, vals_gwo, ylabel, title) in enumerate([
    (acc_all, acc_gwo, 'Accuracy (%)', 'Accuracy: All Features vs GWO-Selected'),
    (f1_all, f1_gwo, 'F1-Macro (%)', 'F1-Macro: All Features vs GWO-Selected'),
    (auc_all, auc_gwo, 'ROC-AUC (%)', 'ROC-AUC: All Features vs GWO-Selected'),
]):
    ax = axes[0, ax_idx]
    bars1 = ax.bar(x - width/2, vals_all, width, label='All Features (79)', color='lightcoral', alpha=0.8, edgecolor='white')
    bars2 = ax.bar(x + width/2, vals_gwo, width, label='GWO-Selected', color='steelblue', alpha=0.8, edgecolor='white')
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.set_xticks(x)
    ax.set_xticklabels(clf_names_all, rotation=35, ha='right', fontsize=9)
    ax.set_ylim([0, 110])
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3, axis='y')
    # Add value labels on bars
    for bar in bars1:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.1f}', ha='center', va='bottom', fontsize=7)
    for bar in bars2:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{height:.1f}', ha='center', va='bottom', fontsize=7)

# Row 2: Delta (improvement from GWO feature selection)
for ax_idx, (vals_delta, ylabel, title) in enumerate([
    (acc_delta, 'Δ Accuracy (%)', 'Accuracy Improvement (GWO - All)'),
    (f1_delta, 'Δ F1-Macro (%)', 'F1 Improvement (GWO - All)'),
    (auc_delta, 'Δ ROC-AUC (%)', 'AUC Improvement (GWO - All)'),
]):
    ax = axes[1, ax_idx]
    colors = ['green' if v > 0 else 'red' for v in vals_delta]
    bars = ax.bar(x, vals_delta, color=colors, alpha=0.7, edgecolor='white')
    ax.axhline(0, color='black', linestyle='-', lw=1)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.set_xticks(x)
    ax.set_xticklabels(clf_names_all, rotation=35, ha='right', fontsize=9)
    ax.grid(alpha=0.3, axis='y')
    # Add value labels
    for bar, val in zip(bars, vals_delta):
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{val:+.1f}%', ha='center', va='bottom' if val > 0 else 'top', fontsize=8)

plt.tight_layout()
plt.savefig('feature_selection_impact.png', bbox_inches='tight', dpi=150)
plt.show()

print('\n' + '='*80)
print('KEY INSIGHTS:')
print('='*80)
print('✓ GREEN = GWO feature selection HELPS this method')
print('✗ RED  = GWO feature selection HURTS this method (overfitting risk)')
print()
best_improved = max(range(len(clf_names_all)), key=lambda i: acc_delta[i])
worst_affected = min(range(len(clf_names_all)), key=lambda i: acc_delta[i])
print(f'Best improvement from feature selection: {clf_names_all[best_improved]} ({acc_delta[best_improved]:+.2f}%)')
print(f'Worst affected by feature selection:     {clf_names_all[worst_affected]} ({acc_delta[worst_affected]:+.2f}%)')
print('='*80)

# ================================================================
# CELL 15 — Save All Results
# ================================================================

pd.DataFrame(fold_results).to_csv('fold_results_cv.csv', index=False)
pd.DataFrame({
    'Feature_Index': selected_idx,
    'Feature_Name': selected_names
}).to_csv('gwo_selected_features.csv', index=False)
pd.DataFrame([best_hp]).to_csv('gwo_best_hyperparams.csv', index=False)

ml = max(len(fs_history), len(hp_history))
pd.DataFrame({
    'iteration': range(1, ml+1),
    'gwo_fs_cost': fs_history + [None]*(ml-len(fs_history)),
    'gwo_hp_cost': hp_history + [None]*(ml-len(hp_history))
}).to_csv('gwo_convergence.csv', index=False)

# Save independent test set results
pd.DataFrame({
    'Test_Accuracy': [test_acc],
    'Test_Sensitivity': [test_sensitivity],
    'Test_Specificity': [test_specificity],
    'Test_F1': [test_f1],
    'Test_AUC': [test_auc],
    'Test_MCC': [test_mcc],
    'Test_Kappa': [test_kappa],
}).to_csv('independent_test_results.csv', index=False)

print('='*70)
print('  FINAL THESIS RESULTS SUMMARY')
print('='*70)
print(f'\nData: {len(y)} total subjects')
print(f'  Training set: {X_train_full.shape[0]} subjects')
print(f'  Test set (held-out): {X_test.shape[0]} subjects')
print(f'  Initial features: {n_features}')
print(f'  After variance filter: {len(feature_names)}')
print(f'  GWO-selected features: {len(selected_idx)}')
print(f'  Selected: {selected_names}')
print(f'\nGWO Configuration:')
print(f'  Feature Selection: {GWO_FS_WOLVES} wolves × {GWO_FS_ITER} iters, α={GWO_FS_ALPHA}')
print(f'  Hyperparameter Tuning: {GWO_HP_WOLVES} wolves × {GWO_HP_ITER} iters')
print(f'  Best Hyperparameters: {best_hp}')
print(f'\n--- 5-FOLD CV RESULTS (Training Set n={X_train_sel.shape[0]}) ---')
print(f'  CV Train Accuracy   : {mt_cv*100:.2f}% ± {np.std(fold_results["train_accuracy"])*100:.2f}%')
print(f'  CV Test Accuracy    : {mv_cv*100:.2f}% ± {np.std(fold_results["accuracy"])*100:.2f}%')
print(f'  Train-Test Gap      : {gap_cv:.2f}%')
print(f'  CV Sensitivity (ASD): {np.mean(fold_results["sensitivity"])*100:.2f}%')
print(f'  CV Specificity (Ctrl): {np.mean(fold_results["specificity"])*100:.2f}%')
print(f'  CV F1-Macro         : {np.mean(fold_results["f1_macro"])*100:.2f}%')
print(f'  CV MCC              : {np.mean(fold_results["mcc"]):.4f}')
print(f'  CV Cohen\'s Kappa    : {np.mean(fold_results["kappa"]):.4f}')
print(f'  CV ROC-AUC          : {np.mean(fold_results["roc_auc"]):.4f} ± {np.std(fold_results["roc_auc"]):.4f}')
print(f'\n--- INDEPENDENT TEST SET RESULTS (n={X_test.shape[0]}) ---')
print(f'  Test Accuracy       : {test_acc*100:.2f}%')
print(f'  Test Sensitivity    : {test_sensitivity*100:.2f}%')
print(f'  Test Specificity    : {test_specificity*100:.2f}%')
print(f'  Test F1-Macro       : {test_f1*100:.2f}%')
print(f'  Test MCC            : {test_mcc:.4f}')
print(f'  Test Cohen\'s Kappa  : {test_kappa:.4f}')
print(f'  Test ROC-AUC        : {test_auc:.4f}')
print(f'\nSMOTE Applied: {USE_SMOTE}')
print('='*70)

# ================================================================
# CELL 16 — Export Model Artifacts for Streamlit Dashboard
#
# This cell saves all necessary files for the dashboard:
# - Trained XGBoost model (pickle)
# - Fitted RobustScaler (pickle)
# - GWO-selected feature names (JSON)
# - Best hyperparameters (JSON)
# - Training statistics for z-score comparison (JSON)
# - Test subject information (JSON)
# - Pre-computed SHAP values (numpy)
# - Full feature matrix CSV (for dashboard feature explorer)
#
# Files are saved to Google Drive for local download.
# ================================================================

import pickle
import json
from pathlib import Path

# Mount Google Drive (if not already mounted)
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

# Create output directories in Google Drive
output_base = '/content/drive/MyDrive/ASD_Dashboard_Artifacts'
model_dir = f'{output_base}/models'
data_dir = f'{output_base}/data'

import os
os.makedirs(model_dir, exist_ok=True)
os.makedirs(data_dir, exist_ok=True)

print('='*70)
print('  EXPORTING MODEL ARTIFACTS FOR DASHBOARD')
print('='*70)

# ============================================================
# 1. Save the trained XGBoost model
# ============================================================
# Using the final_test_model from Cell 7 (trained on full training set)
# This is the model used for independent test set evaluation

with open(f'{model_dir}/gwo_xgboost_model.pkl', 'wb') as f:
    pickle.dump(final_test_model, f)
print('✓ [1/8] Trained XGBoost model saved')

# ============================================================
# 2. Save the fitted RobustScaler
# ============================================================
# sc_final was fitted on X_train_sel in Cell 7

with open(f'{model_dir}/scaler.pkl', 'wb') as f:
    pickle.dump(sc_final, f)
print('✓ [2/8] RobustScaler saved')

# ============================================================
# 3. Save GWO-selected feature names
# ============================================================
with open(f'{model_dir}/gwo_selected_features.json', 'w') as f:
    json.dump(selected_names, f, indent=2)
print(f'✓ [3/8] GWO-selected features saved ({len(selected_names)} features)')

# ============================================================
# 4. Save best hyperparameters
# ============================================================
# Convert any numpy types to Python native types for JSON serialization
best_hp_serializable = {}
for k, v in best_hp.items():
    if isinstance(v, (np.integer,)):
        best_hp_serializable[k] = int(v)
    elif isinstance(v, (np.floating,)):
        best_hp_serializable[k] = float(v)
    else:
        best_hp_serializable[k] = v

with open(f'{model_dir}/best_hyperparameters.json', 'w') as f:
    json.dump(best_hp_serializable, f, indent=2)
print('✓ [4/8] Best hyperparameters saved')

# ============================================================
# 5. Save training statistics (for z-score comparison in dashboard)
# ============================================================
# Compute mean/std/min/max of GWO-selected features on training set
# Also compute per-class means for radar chart comparison

train_stats = {}
X_train_sel_df = pd.DataFrame(X_train_sel, columns=selected_names)

for col in selected_names:
    col_data = X_train_sel_df[col]
    col_asd = X_train_sel_df[col][y_train_full == 1]
    col_ctrl = X_train_sel_df[col][y_train_full == 0]

    train_stats[col] = {
        'mean': float(col_data.mean()),
        'std': float(col_data.std()),
        'min': float(col_data.min()),
        'max': float(col_data.max()),
        'median': float(col_data.median()),
        'asd_mean': float(col_asd.mean()),
        'asd_std': float(col_asd.std()),
        'control_mean': float(col_ctrl.mean()),
        'control_std': float(col_ctrl.std()),
    }

with open(f'{model_dir}/training_stats.json', 'w') as f:
    json.dump(train_stats, f, indent=2)
print('✓ [5/8] Training statistics saved')

# ============================================================
# 6. Save test subject information
# ============================================================
test_info = {
    'subjects': test_subjects,
    'labels': y_test.tolist(),
    'n_test': len(y_test),
    'n_train': len(y_train_full),
    'predictions': y_test_pred.tolist(),
    'probabilities_asd': y_test_prob[:, 1].tolist(),
    'probabilities_control': y_test_prob[:, 0].tolist(),
    'test_accuracy': float(test_acc),
    'test_auc': float(test_auc),
}

with open(f'{data_dir}/test_subjects.json', 'w') as f:
    json.dump(test_info, f, indent=2)
print(f'✓ [6/8] Test subject info saved ({len(test_subjects)} subjects)')

# ============================================================
# 7. Pre-compute and save SHAP values
# ============================================================
# Use the SHAP model from Cell 11/12 (trained on full training set)
# Save SHAP values for all training subjects

# Re-compute if not already available from Cell 12
try:
    # sv should already exist from Cell 12
    np.save(f'{data_dir}/shap_values_train.npy', sv)
    print(f'✓ [7/8] SHAP values saved (shape: {sv.shape})')
except NameError:
    # If sv doesn't exist, recompute
    explainer_export = shap.TreeExplainer(final_test_model)
    X_train_scaled_export = sc_final.transform(X_train_sel)
    sv_export = explainer_export.shap_values(X_train_scaled_export)
    if isinstance(sv_export, list):
        sv_export = sv_export[1]
    np.save(f'{data_dir}/shap_values_train.npy', sv_export)
    print(f'✓ [7/8] SHAP values computed and saved (shape: {sv_export.shape})')

# Also compute SHAP for test subjects
X_test_scaled_export = sc_final.transform(X_test_sel)
explainer_test = shap.TreeExplainer(final_test_model)
sv_test = explainer_test.shap_values(X_test_scaled_export)
if isinstance(sv_test, list):
    sv_test = sv_test[1]
np.save(f'{data_dir}/shap_values_test.npy', sv_test)
print(f'    Also saved test SHAP values (shape: {sv_test.shape})')

# Save SHAP expected value (base value)
expected_value = explainer_test.expected_value
if isinstance(expected_value, (list, np.ndarray)):
    expected_value = expected_value[1] if len(expected_value) > 1 else expected_value[0]
with open(f'{data_dir}/shap_expected_value.json', 'w') as f:
    json.dump({'expected_value': float(expected_value)}, f)

# ============================================================
# 8. Save the full feature matrix CSV (for dashboard)
# ============================================================
# Save the original CSV with labels for the feature explorer
df_raw.to_csv(f'{data_dir}/features_sheffield_v3 - features_sheffield_v3.csv.csv', index=False)
print('✓ [8/8] Full feature matrix CSV saved')

# ============================================================
# BONUS: Save additional useful data
# ============================================================

# Save all feature names (79 features)
with open(f'{data_dir}/all_feature_names.json', 'w') as f:
    json.dump(feature_names, f, indent=2)

# Save GWO convergence history
convergence_data = {
    'fs_history': fs_history,
    'hp_history': hp_history,
    'fs_config': {
        'wolves': GWO_FS_WOLVES,
        'iterations': GWO_FS_ITER,
        'alpha': GWO_FS_ALPHA
    },
    'hp_config': {
        'wolves': GWO_HP_WOLVES,
        'iterations': GWO_HP_ITER
    }
}
with open(f'{data_dir}/gwo_convergence.json', 'w') as f:
    json.dump(convergence_data, f, indent=2)

# Save CV fold results
with open(f'{data_dir}/cv_fold_results.json', 'w') as f:
    json.dump({k: [float(x) for x in v] if isinstance(v[0], (float, np.floating))
               else v for k, v in fold_results.items()}, f, indent=2)

# Save model metadata
model_metadata = {
    'model_type': 'XGBoost',
    'optimization': 'Grey Wolf Optimizer (GWO)',
    'n_features_total': int(n_features),
    'n_features_selected': len(selected_idx),
    'feature_reduction_pct': round((1 - len(selected_idx)/n_features) * 100, 1),
    'selected_features': selected_names,
    'best_hyperparameters': best_hp_serializable,
    'cv_accuracy': round(float(mv_cv * 100), 2),
    'cv_accuracy_std': round(float(np.std(fold_results['accuracy']) * 100), 2),
    'cv_auc': round(float(np.mean(fold_results['roc_auc'])), 4),
    'cv_sensitivity': round(float(np.mean(fold_results['sensitivity']) * 100), 2),
    'cv_specificity': round(float(np.mean(fold_results['specificity']) * 100), 2),
    'cv_f1_macro': round(float(np.mean(fold_results['f1_macro']) * 100), 2),
    'test_accuracy': round(float(test_acc * 100), 2),
    'test_auc': round(float(test_auc), 4),
    'test_sensitivity': round(float(test_sensitivity * 100), 2),
    'test_specificity': round(float(test_specificity * 100), 2),
    'n_subjects_total': int(n_samples),
    'n_subjects_train': int(X_train_full.shape[0]),
    'n_subjects_test': int(X_test.shape[0]),
    'dataset': 'Sheffield EEG Autism Dataset',
    'random_seed': SEED,
    'smote_applied': USE_SMOTE,
}
with open(f'{model_dir}/model_metadata.json', 'w') as f:
    json.dump(model_metadata, f, indent=2)

print('\n' + '='*70)
print('  ALL ARTIFACTS EXPORTED SUCCESSFULLY')
print('='*70)
print(f'\n  Output location: {output_base}')
print(f'\n  Directory structure:')
print(f'  {output_base}/')
print(f'  ├── models/')
print(f'  │   ├── gwo_xgboost_model.pkl')
print(f'  │   ├── scaler.pkl')
print(f'  │   ├── gwo_selected_features.json')
print(f'  │   ├── best_hyperparameters.json')
print(f'  │   ├── training_stats.json')
print(f'  │   └── model_metadata.json')
print(f'  └── data/')
print(f'      ├── features_sheffield_v3.csv')
print(f'      ├── test_subjects.json')
print(f'      ├── shap_values_train.npy')
print(f'      ├── shap_values_test.npy')
print(f'      ├── shap_expected_value.json')
print(f'      ├── all_feature_names.json')
print(f'      ├── gwo_convergence.json')
print(f'      └── cv_fold_results.json')
print(f'\n  Next steps:')
print(f'  1. Download the "{output_base}" folder from Google Drive')
print(f'  2. Place "models/" and "data/" inside your dashboard project')
print(f'  3. Run: streamlit run app.py')
print('='*70)